-----------------------------------------------------------------------------
-- |
-- Copyright   : (C) 2015 Dimitri Sabadie
-- License     : BSD3
--
-- Maintainer  : Dimitri Sabadie <dimitri.sabadie@gmail.com>
-- Stability   : experimental
-- Portability : portable
--
----------------------------------------------------------------------------

module Qzr.New.Shader (
    -- * Create new shader Haskell modules
    newShader
  ) where

newShader :: String -> IO ()
newShader name = writeFile (name <.> "hs") (shaderTemplate name)

shaderTemplate :: String -> String
shaderTemplate name = unlines
  [
    replicate 79 '-'
  , "-- generated by: qzr new shader"
  , replicate 79 '-'
  , "module " ++ name ++ " where"
  , ""
  , "shaderStage :: String"
  , "shaderStage = unlines"
  , "  ["
  , "    -- Available vertex shader inputs:"
  , "    --   * [vec3]             0    : vertex's coordinates"
  , "    --   * [vec3]             1    : vertex's normal"
  , "    --   * [vec2]             2    : vertex's UV coordinates"
  , "    --"
  , "    -- Available uniform semantics:"
  , "    --   * [mat4]             0    : camera projection matrix"
  , "    --   * [mat4]             1    : model matrix"
  , "    --   * [vec3]             2    : camera position"
  , "    --   * [vec3]             3    : ambient light color"
  , "    --   * [float]            4    : ambient light power"
  , "    --   * [uint]             5    : number of omnidirectional lights"
  , "    --   * [mat4]             6-11 : omnidirectional view matrices"
  , "    --   *                      6  : +X"
  , "    --   *                      7  : -X"
  , "    --   *                      8  : +Y"
  , "    --   *                      9  : -Y"
  , "    --   *                      10 : +Z"
  , "    --   *                      11 : -Z"
  , "    --   * [samplerCubeArray] 16   : low shadow cubemap array"
  , "    --   * [samplerCubeArray] 17   : medium shadow cubemap array"
  , "    --   * [samplerCubeArray] 18   : high shadow cubemap array"
  , "    --"
  , "    -- Available uniform block binding points:"
  , "    --   * [OmniBuffer]       0    : buffer of omnidirectional lights"
  , "    --"
  , "    -- Built-in structures:"
  , "    \"struct Omni {\""
  , "  , \"  vec3 pos;\""
  , "  , \"  vec3 col;\""
  , "  , \"  float pow;\""
  , "  , \"  float rad;\""
  , "  , \"  uint shadowLOD;\""
  , "  , \"  uint shadowmapIndex;\""
  , "  , \" };\""
  , "  ]"
  ]
